// This file is generated by `npx convex dev`
// Run `npx convex dev` to generate the real API

export const api = {
  missions: {
    submitMission: "missions:submitMission",
    getMissions: "missions:getMissions",
    getMission: "missions:getMission",
    upvoteMission: "missions:upvoteMission",
  },
  comments: {
    submitComment: "comments:submitComment",
    getComments: "comments:getComments",
  },
};

export const internal = {
  missions: {
    submitMission: "missions:submitMission",
    getMissions: "missions:getMissions",
    getMission: "missions:getMission",
    upvoteMission: "missions:upvoteMission",
  },
  comments: {
    submitComment: "comments:submitComment",
    getComments: "comments:getComments",
  },
};