// This file is generated by `npx convex dev`
// Run `npx convex dev` to generate the real data model

export interface Id<T> {
  table: T;
  __type: "Id";
}

export interface DataModel {
  missions: {
    design: any;
    scorecard: any;
    missionId: string;
    missionName: string;
    destination: "moon" | "mars";
    vehicleName: string;
    crew: number;
    surfaceDays: number;
    grade: string;
    score: number;
    createdAt: number;
    upvotes: number;
    authorId: string;
    authorName?: string;
    commentCount: number;
  };
  comments: {
    missionId: string;
    text: string;
    authorId: string;
    authorName?: string;
    createdAt: number;
  };
}