// This file is generated by `npx convex dev`
// Run `npx convex dev` to generate the real server types

export { mutationGeneric as mutation, queryGeneric as query, actionGeneric as action } from "convex/server";
export type { FunctionReference, FunctionReturnType } from "convex/server";